services:
  pamukky-server:
#    Uncomment the following lines if you want to do local builds:
#    build:
#      context: .
#      dockerfile: Dockerfile
#
#    Comment the next line if you want to do local builds:
    image: ghcr.io/kuskebabi/pamukkyv3server:latest
    container_name: pamukky-server
    ports:
      - "4268:4268"
    volumes:
      - ./data:/App/data
      - ./config.json:/App/config.json:ro
      - ./tos.txt:/App/tos.txt:ro
    restart: unless-stopped
    user: "1000:1000"
    stdin_open: true
    tty: true
    environment:
      - ASPNETCORE_URLS=http://+:4268
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        #reservations:
        #  cpus: '0.25'
        #  memory: 256M
